const mockdetails = [
    {
        id: Math.random().toString(36).substr(1,10),
        airplane: "Airbus A320-200",
        name: "LH099",
        von: "Muechen",
        vonGate: "Terminal 2, Gate G30",
        nach: "Frankfurt",
        nachGate: "Termianl 1, Gate A34",
        departure: "09:00",
        arrive: "10:00",
        plan: true,
    },
    {
        id: Math.random().toString(36).substr(1,10),
        airplane: "Airbus A320-200",
        name: "LH100",
        von: "Muechen",
        vonGate: "Terminal 2, Gate G30",
        nach: "Frankfurt",
        nachGate: "Termianl 1, Gate A34",
        departure: "10:00",
        arrive: "11:00",
        plan: true,
    },
    {
        id: Math.random().toString(36).substr(1,10),
        airplane: "Airbus A320-200",
        name: "LH101",
        von: "Muechen",
        vonGate: "Terminal 2, Gate G30",
        nach: "Frankfurt",
        nachGate: "Termianl 1, Gate A34",
        departure: "11:00",
        arrive: "12:00",
        plan: true,
    },
    {
        id: Math.random().toString(36).substr(1,10),
        airplane: "Airbus A320-200",
        name: "LH102",
        von: "Muechen",
        vonGate: "Terminal 2, Gate G30",
        nach: "Frankfurt",
        nachGate: "Termianl 1, Gate A34",
        departure: "12:00",
        arrive: "13:00",
        plan: true,
    },
    {
        id: Math.random().toString(36).substr(1,10),
        airplane: "Airbus A320-200",
        name: "LH103",
        von: "Muechen",
        vonGate: "Terminal 2, Gate G30",
        nach: "Frankfurt",
        nachGate: "Termianl 1, Gate A34",
        departure: "13:00",
        arrive: "14:00",
        plan: true,
    },
    {
        id: Math.random().toString(36).substr(1,10),
        airplane: "Airbus A320-200",
        name: "LH099",
        von: "Muechen",
        vonGate: "Terminal 2, Gate G30",
        nach: "Frankfurt",
        nachGate: "Termianl 1, Gate A34",
        departure: "09:00",
        arrive: "10:00",
        plan: true,
    },
    {
        id: Math.random().toString(36).substr(1,10),
        airplane: "Airbus A320-200",
        name: "LH100",
        von: "Muechen",
        vonGate: "Terminal 2, Gate G30",
        nach: "Frankfurt",
        nachGate: "Termianl 1, Gate A34",
        departure: "10:00",
        arrive: "11:00",
        plan: true,
    },
    {
        id: Math.random().toString(36).substr(1,10),
        airplane: "Airbus A320-200",
        name: "LH101",
        von: "Muechen",
        vonGate: "Terminal 2, Gate G30",
        nach: "Frankfurt",
        nachGate: "Termianl 1, Gate A34",
        departure: "11:00",
        arrive: "12:00",
        plan: true,
    },
    {
        id: Math.random().toString(36).substr(1,10),
        airplane: "Airbus A320-200",
        name: "LH102",
        von: "Muechen",
        vonGate: "Terminal 2, Gate G30",
        nach: "Frankfurt",
        nachGate: "Termianl 1, Gate A34",
        departure: "12:00",
        arrive: "13:00",
        plan: true,
    },
    {
        id: Math.random().toString(36).substr(1,10),
        airplane: "Airbus A320-200",
        name: "LH103",
        von: "Muechen",
        vonGate: "Terminal 2, Gate G30",
        nach: "Frankfurt",
        nachGate: "Termianl 1, Gate A34",
        departure: "13:00",
        arrive: "14:00",
        plan: true,
    },
    {
        id: Math.random().toString(36).substr(1,10),
        airplane: "Airbus A320-200",
        name: "LH099",
        von: "Muechen",
        vonGate: "Terminal 2, Gate G30",
        nach: "Frankfurt",
        nachGate: "Termianl 1, Gate A34",
        departure: "09:00",
        arrive: "10:00",
        plan: true,
    },
    {
        id: Math.random().toString(36).substr(1,10),
        airplane: "Airbus A320-200",
        name: "LH100",
        von: "Muechen",
        vonGate: "Terminal 2, Gate G30",
        nach: "Frankfurt",
        nachGate: "Termianl 1, Gate A34",
        departure: "10:00",
        arrive: "11:00",
        plan: true,
    },
    {
        id: Math.random().toString(36).substr(1,10),
        airplane: "Airbus A320-200",
        name: "LH101",
        von: "Muechen",
        vonGate: "Terminal 2, Gate G30",
        nach: "Frankfurt",
        nachGate: "Termianl 1, Gate A34",
        departure: "11:00",
        arrive: "12:00",
        plan: true,
    },
    {
        id: Math.random().toString(36).substr(1,10),
        airplane: "Airbus A320-200",
        name: "LH102",
        von: "Muechen",
        vonGate: "Terminal 2, Gate G30",
        nach: "Frankfurt",
        nachGate: "Termianl 1, Gate A34",
        departure: "12:00",
        arrive: "13:00",
        plan: true,
    },
    {
        id: Math.random().toString(36).substr(1,10),
        airplane: "Airbus A320-200",
        name: "LH103",
        von: "Muechen",
        vonGate: "Terminal 2, Gate G30",
        nach: "Frankfurt",
        nachGate: "Termianl 1, Gate A34",
        departure: "13:00",
        arrive: "14:00",
        plan: true,
    },
    {
        id: Math.random().toString(36).substr(1,10),
        airplane: "Airbus A320-200",
        name: "LH099",
        von: "Muechen",
        vonGate: "Terminal 2, Gate G30",
        nach: "Frankfurt",
        nachGate: "Termianl 1, Gate A34",
        departure: "09:00",
        arrive: "10:00",
        plan: true,
    },
    {
        id: Math.random().toString(36).substr(1,10),
        airplane: "Airbus A320-200",
        name: "LH100",
        von: "Muechen",
        vonGate: "Terminal 2, Gate G30",
        nach: "Frankfurt",
        nachGate: "Termianl 1, Gate A34",
        departure: "10:00",
        arrive: "11:00",
        plan: true,
    },
    {
        id: Math.random().toString(36).substr(1,10),
        airplane: "Airbus A320-200",
        name: "LH101",
        von: "Muechen",
        vonGate: "Terminal 2, Gate G30",
        nach: "Frankfurt",
        nachGate: "Termianl 1, Gate A34",
        departure: "11:00",
        arrive: "12:00",
        plan: true,
    },
    {
        id: Math.random().toString(36).substr(1,10),
        airplane: "Airbus A320-200",
        name: "LH102",
        von: "Muechen",
        vonGate: "Terminal 2, Gate G30",
        nach: "Frankfurt",
        nachGate: "Termianl 1, Gate A34",
        departure: "12:00",
        arrive: "13:00",
        plan: true,
    },
    {
        id: Math.random().toString(36).substr(1,10),
        airplane: "Airbus A320-200",
        name: "LH103",
        von: "Muechen",
        vonGate: "Terminal 2, Gate G30",
        nach: "Frankfurt",
        nachGate: "Termianl 1, Gate A34",
        departure: "13:00",
        arrive: "14:00",
        plan: true,
    }

]