let mockFlight = [
    {
        id: Math.random().toString(36).substr(1,10), 
        name: "LH099",
        nach: "Frankfurt",
        departure: "09:00",
        arrive: "10:00",
        plan: true,
    },
    {
        id: Math.random().toString(36).substr(1,10), 
        name: "LH100",
        nach: "Frankfurt",
        departure: "09:00",
        arrive: "10:00",
        plan: true,
    },
    {
        id: Math.random().toString(36).substr(1,10), 
        name: "LH101",
        nach: "Frankfurt",
        departure: "09:00",
        arrive: "10:00",
        plan: true,
    },
    {
        id: Math.random().toString(36).substr(1,10), 
        name: "LH102",
        nach: "Frankfurt",
        departure: "09:00",
        arrive: "10:00",
        plan: true,
    },
    {
        id: Math.random().toString(36).substr(1,10), 
        name: "LH103",
        nach: "Frankfurt",
        departure: "09:00",
        arrive: "10:00",
        plan: true,
    },
    {
        id: Math.random().toString(36).substr(1,10), 
        name: "LH099",
        nach: "Frankfurt",
        departure: "09:00",
        arrive: "10:00",
        plan: true,
    },
    {
        id: Math.random().toString(36).substr(1,10), 
        name: "LH100",
        nach: "Frankfurt",
        departure: "09:00",
        arrive: "10:00",
        plan: true,
    },
    {
        id: Math.random().toString(36).substr(1,10), 
        name: "LH101",
        nach: "Frankfurt",
        departure: "09:00",
        arrive: "10:00",
        plan: true,
    },
    {
        id: Math.random().toString(36).substr(1,10), 
        name: "LH102",
        nach: "Frankfurt",
        departure: "09:00",
        arrive: "10:00",
        plan: true,
    },
    {
        id: Math.random().toString(36).substr(1,10), 
        name: "LH103",
        nach: "Frankfurt",
        departure: "09:00",
        arrive: "10:00",
        plan: true,
    },
    {
        id: Math.random().toString(36).substr(1,10), 
        name: "LH099",
        nach: "Frankfurt",
        departure: "09:00",
        arrive: "10:00",
        plan: true,
    },
    {
        id: Math.random().toString(36).substr(1,10), 
        name: "LH100",
        nach: "Frankfurt",
        departure: "09:00",
        arrive: "10:00",
        plan: true,
    },
    {
        id: Math.random().toString(36).substr(1,10), 
        name: "LH101",
        nach: "Frankfurt",
        departure: "09:00",
        arrive: "10:00",
        plan: true,
    },
    {
        id: Math.random().toString(36).substr(1,10), 
        name: "LH102",
        nach: "Frankfurt",
        departure: "09:00",
        arrive: "10:00",
        plan: true,
    },
    {
        id: Math.random().toString(36).substr(1,10), 
        name: "LH103",
        nach: "Frankfurt",
        departure: "09:00",
        arrive: "10:00",
        plan: true,
    },
    {
        id: Math.random().toString(36).substr(1,10), 
        name: "LH099",
        nach: "Frankfurt",
        departure: "09:00",
        arrive: "10:00",
        plan: true,
    },
    {
        id: Math.random().toString(36).substr(1,10), 
        name: "LH100",
        nach: "Frankfurt",
        departure: "09:00",
        arrive: "10:00",
        plan: true,
    },
    {
        id: Math.random().toString(36).substr(1,10), 
        name: "LH101",
        nach: "Frankfurt",
        departure: "09:00",
        arrive: "10:00",
        plan: true,
    },
    {
        id: Math.random().toString(36).substr(1,10), 
        name: "LH102",
        nach: "Frankfurt",
        departure: "09:00",
        arrive: "10:00",
        plan: true,
    },
    {
        id: Math.random().toString(36).substr(1,10), 
        name: "LH103",
        nach: "Frankfurt",
        departure: "09:00",
        arrive: "10:00",
        plan: true,
    },
    {
        id: Math.random().toString(36).substr(1,10), 
        name: "LH099",
        nach: "Frankfurt",
        departure: "09:00",
        arrive: "10:00",
        plan: true,
    },
    {
        id: Math.random().toString(36).substr(1,10), 
        name: "LH100",
        nach: "Frankfurt",
        departure: "09:00",
        arrive: "10:00",
        plan: true,
    },
    {
        id: Math.random().toString(36).substr(1,10), 
        name: "LH101",
        nach: "Frankfurt",
        departure: "09:00",
        arrive: "10:00",
        plan: true,
    },
    {
        id: Math.random().toString(36).substr(1,10), 
        name: "LH102",
        nach: "Frankfurt",
        departure: "09:00",
        arrive: "10:00",
        plan: true,
    },
    {
        id: Math.random().toString(36).substr(1,10), 
        name: "LH103",
        nach: "Frankfurt",
        departure: "09:00",
        arrive: "10:00",
        plan: true,
    }
]